use_frameworks!

target 'MRubyKit_Example' do
  pod 'MRubyKit', :path => '../'

  target 'MRubyKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
